project:
  type: website

website:
  title: ""
  favicon: img/Logo.png
  draft-mode: unlinked
  navbar:
    tools:
    - icon: linkedin
      href: https://www.linkedin.com/in/stephan-smeekes/
    - icon: github
      href: https://github.com/smeekes
    background: primary
    foreground: light
    logo: "img/wlogoUM.png"
    logo-href: "https://www.maastrichtuniversity.nl/"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - research.qmd
      - software.qmd
      - teaching.qmd
      - href: more.qmd
        text: More

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    toc-location: left
    toc-expand: true
    link-external-newwindow: true
    reference-location: margin
    respect-user-color-scheme: true
